SELECT FLAVOR
FROM (
    SELECT H.FLAVOR, COALESCE(SUM(H.TOTAL_ORDER), 0) + COALESCE(SUM(J.TOTAL_ORDER), 0) AS TOTAL_ORDER
    FROM FIRST_HALF H
    LEFT JOIN JULY J ON H.FLAVOR = J.FLAVOR
    GROUP BY H.FLAVOR

    UNION ALL

    SELECT J.FLAVOR, COALESCE(SUM(H.TOTAL_ORDER), 0) + COALESCE(SUM(J.TOTAL_ORDER), 0) AS TOTAL_ORDER
    FROM JULY J
    LEFT JOIN FIRST_HALF H ON J.FLAVOR = H.FLAVOR
    WHERE H.FLAVOR IS NULL
    GROUP BY J.FLAVOR
) AS TOTALS
ORDER BY TOTAL_ORDER DESC
LIMIT 3;
